### ISSUE TITLE
Refinement: Update meta-data

### ISSUE THREAD

**Issue by stijn-dejongh** [sddevelopment-be/penguin-pragmatic-patterns#64]
# Metadata upgrade

## Description

Update the metadata of all concepts and practices to include:

- Adherence to new Concept and Practice structure
- New style AMMERSE values
- Internal references through 'related_concepts' and 'related_practices'
- References to bibliography entries ( through 'further exploration' )
- References to tools and external websites (through 'further exploration' )
- A 'description' and 'summary' field

The basic visualization processors are already in place, the content needs to be updated to properly feed them.

### Practices

* [x] AMMERSE Impact Analysis
* [x] Avoid Gold Plating
* [x] Interviewing like a STARR
* [x] Set stopping conditions
* [x] Synced Style
* [x] Defining Test Boundaries
* [x] Don't run out of STEAM
* [x] Get your priorities straight
* [x] Write chat messages as mini-emails
* [x] Use an External Memory
* [x] Fail Fast, Formulate Feedback!
* [x] Plan a self-sabotage
* [x] Keep a changelog
* [x] Listening to Understand: The LARS Approach for Improved Conversations
* [x] Mind Mapping: visualizing a topic
* [x] The OPERAs method
* [x] Organize your workflow
* [x] Pomodoro Focus
* [x] Safe to fail experiments
* [x] Build your knowledge portfolio
* [x] Ten Minute Tasks
* [x] Find the source of dissent
* [x] Traceable decisions
* [x] Wax on, wax off 

### Concepts

* [x] Chain of Accountability
* [x] Your circle of influence
* [x] Clean code
* [x] Cognitive Biases
* [x] Dreyfus model
* [x] Heartfelt Dialogues
* [x] Lewin's Leadership Styles
* [x] Memento Mori
* [x] Red versus Blue work
* [x] Return On Investment
* [x] Shu Ha Ri
* [x] Software Architecture
* [x] Thinking in Systems
* [x] Test Driven Development
* [x] The Testing Pyramid
